site_name: Kirby Uniform
site_description: A versatile Kirby 2 plugin to handle web form actions.
site_author: Martin Zurowietz
site_url: https://github.com/mzur/kirby-uniform/
repo_url: https://github.com/mzur/kirby-uniform/
edit_uri: blob/master/docs/
pages:
    - Home: index.md
    - Usage: usage.md
    - Methods: methods.md
    - Guards:
        - Guards: guards/guards.md
        - Honeypot: guards/honeypot.md
        - Calc: guards/calc.md
        - reCAPTCHA: guards/recaptcha.md
    - Actions:
        - Actions: actions/actions.md
        - Email: actions/email.md
        - Email Select: actions/email-select.md
        - Log: actions/log.md
        - Login: actions/login.md
        - Webhook: actions/webhook.md
        - 'Session Store': actions/session-store.md
        - Upload: actions/upload.md
    - Examples:
        - Basic: examples/basic.md
        - Extended: examples/extended.md
        - AJAX: examples/ajax.md
    - Answers: answers.md
    - 'Upgrade Guide': upgrade-guide.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition:
