site_name: Kirby Uniform
site_description: A versatile Kirby plugin to handle web form actions.
site_author: Martin Zurowietz
site_url: https://github.com/mzur/kirby-uniform/
repo_url: https://github.com/mzur/kirby-uniform/
edit_uri: blob/master/docs/
nav:
    - Home: index.md
    - Usage: usage.md
    - Methods: methods.md
    - Guards:
        - Guards: guards/guards.md
        - Honeypot: guards/honeypot.md
        - Honeytime: guards/honeytime.md
        - SimpleCaptcha: guards/simple-captcha.md
        - Calc: guards/calc.md
        - reCAPTCHA: guards/recaptcha.md
    - Actions:
        - Actions: actions/actions.md
        - Email: actions/email.md
        - Email Select: actions/email-select.md
        - Log: actions/log.md
        - Login: actions/login.md
        - Webhook: actions/webhook.md
        - 'Session Store': actions/session-store.md
        - Upload: actions/upload.md
    - Examples:
        - Basic: examples/basic.md
        - Building Blocks: examples/blocks.md
        - Extended: examples/extended.md
        - AJAX: examples/ajax.md
        - Dynamic Fields: examples/dynamic.md
    - Answers: answers.md
    - 'Upgrade Guide v4->v5': upgrade-guide-v4-v5.md
    - 'Upgrade Guide v3->v4': upgrade-guide-v3-v4.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: ïƒ
    - admonition:
