blank_issues_enabled: false
contact_links:
  - name: Kirby Forum
    url: https://forum.getkirby.com/
    about: If you don't want to report a bug or request a new feature, please ask for help in the official Kirby forum.
